//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMeanInit.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class SettingsBase : global::System.Configuration.ApplicationSettingsBase {
        
        private static SettingsBase defaultInstance = ((SettingsBase)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new SettingsBase())));
        
        public static SettingsBase Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int k_mean_rules_generator_conf_type_func {
            get {
                return ((int)(this["k_mean_rules_generator_conf_type_func"]));
            }
            set {
                this["k_mean_rules_generator_conf_type_func"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int k_mean_rules_generator_conf_count_rules {
            get {
                return ((int)(this["k_mean_rules_generator_conf_count_rules"]));
            }
            set {
                this["k_mean_rules_generator_conf_count_rules"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int k_mean_rules_generator_conf_Max_iterate {
            get {
                return ((int)(this["k_mean_rules_generator_conf_Max_iterate"]));
            }
            set {
                this["k_mean_rules_generator_conf_Max_iterate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.001")]
        public double k_mean_rules_generator_conf_need_precision {
            get {
                return ((double)(this["k_mean_rules_generator_conf_need_precision"]));
            }
            set {
                this["k_mean_rules_generator_conf_need_precision"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public double k_mean_rules_generator_conf_nebulisation_factor {
            get {
                return ((double)(this["k_mean_rules_generator_conf_nebulisation_factor"]));
            }
            set {
                this["k_mean_rules_generator_conf_nebulisation_factor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int k_mean_rules_generator_conf_type_alg {
            get {
                return ((int)(this["k_mean_rules_generator_conf_type_alg"]));
            }
            set {
                this["k_mean_rules_generator_conf_type_alg"] = value;
            }
        }
    }
}
