//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultiGoal.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int ThreeMultiGoal_Iterrate {
            get {
                return ((int)(this["ThreeMultiGoal_Iterrate"]));
            }
            set {
                this["ThreeMultiGoal_Iterrate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.0001")]
        public double ThreeMultiGoal_stepPercent {
            get {
                return ((double)(this["ThreeMultiGoal_stepPercent"]));
            }
            set {
                this["ThreeMultiGoal_stepPercent"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double ThreeMultiGoal_stepCoplexity {
            get {
                return ((double)(this["ThreeMultiGoal_stepCoplexity"]));
            }
            set {
                this["ThreeMultiGoal_stepCoplexity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.03")]
        public double ThreeMultiGoal_stepIterability {
            get {
                return ((double)(this["ThreeMultiGoal_stepIterability"]));
            }
            set {
                this["ThreeMultiGoal_stepIterability"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public double ThreeMultiGoal_stepDivider {
            get {
                return ((double)(this["ThreeMultiGoal_stepDivider"]));
            }
            set {
                this["ThreeMultiGoal_stepDivider"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int ThreeMultiGoal_stepTries {
            get {
                return ((int)(this["ThreeMultiGoal_stepTries"]));
            }
            set {
                this["ThreeMultiGoal_stepTries"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int ThreeMultiGoal_countSysteminCell {
            get {
                return ((int)(this["ThreeMultiGoal_countSysteminCell"]));
            }
            set {
                this["ThreeMultiGoal_countSysteminCell"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ThreeMultiGoal_typeComplexity {
            get {
                return ((int)(this["ThreeMultiGoal_typeComplexity"]));
            }
            set {
                this["ThreeMultiGoal_typeComplexity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ThreeMultiGoal_typeInterpreting {
            get {
                return ((int)(this["ThreeMultiGoal_typeInterpreting"]));
            }
            set {
                this["ThreeMultiGoal_typeInterpreting"] = value;
            }
        }
    }
}
