//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShrinkMethods.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    public sealed partial class SettingsBase : global::System.Configuration.ApplicationSettingsBase {
        
        private static SettingsBase defaultInstance = ((SettingsBase)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new SettingsBase())));
        
        public static SettingsBase Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int Pareto_simpler_Request_count_rules {
            get {
                return ((int)(this["Pareto_simpler_Request_count_rules"]));
            }
            set {
                this["Pareto_simpler_Request_count_rules"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int Term_shrink_and_rotate_conf_count_shrink {
            get {
                return ((int)(this["Term_shrink_and_rotate_conf_count_shrink"]));
            }
            set {
                this["Term_shrink_and_rotate_conf_count_shrink"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int Term_shrink_and_rotate_conf_size_of_shrink {
            get {
                return ((int)(this["Term_shrink_and_rotate_conf_size_of_shrink"]));
            }
            set {
                this["Term_shrink_and_rotate_conf_size_of_shrink"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int Pareto_simpler_count_shrink_rules {
            get {
                return ((int)(this["Pareto_simpler_count_shrink_rules"]));
            }
            set {
                this["Pareto_simpler_count_shrink_rules"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Pareto_simpler_Rules {
            get {
                return ((bool)(this["Pareto_simpler_Rules"]));
            }
            set {
                this["Pareto_simpler_Rules"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Pareto_simpler_Terms {
            get {
                return ((bool)(this["Pareto_simpler_Terms"]));
            }
            set {
                this["Pareto_simpler_Terms"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int Term_shrink_HardCode_size_of_shrink {
            get {
                return ((int)(this["Term_shrink_HardCode_size_of_shrink"]));
            }
            set {
                this["Term_shrink_HardCode_size_of_shrink"] = value;
            }
        }
    }
}
