//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaseInitMethods.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class SettingsBase : global::System.Configuration.ApplicationSettingsBase {
        
        private static SettingsBase defaultInstance = ((SettingsBase)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new SettingsBase())));
        
        public static SettingsBase Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Type_func_int {
            get {
                return ((int)(this["Type_func_int"]));
            }
            set {
                this["Type_func_int"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int Count_vars {
            get {
                return ((int)(this["Count_vars"]));
            }
            set {
                this["Count_vars"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int AvrCountTerms {
            get {
                return ((int)(this["AvrCountTerms"]));
            }
            set {
                this["AvrCountTerms"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\"\"")]
        public string Load_UFS_file_name {
            get {
                return ((string)(this["Load_UFS_file_name"]));
            }
            set {
                this["Load_UFS_file_name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int init_everyone_with_everyone_func {
            get {
                return ((int)(this["init_everyone_with_everyone_func"]));
            }
            set {
                this["init_everyone_with_everyone_func"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Generator_Rulles_simples_random_stable {
            get {
                return ((int)(this["Generator_Rulles_simples_random_stable"]));
            }
            set {
                this["Generator_Rulles_simples_random_stable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Generator_Rulles_simples_random_func {
            get {
                return ((int)(this["Generator_Rulles_simples_random_func"]));
            }
            set {
                this["Generator_Rulles_simples_random_func"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int Generator_Rulles_simples_random_сount_rules {
            get {
                return ((int)(this["Generator_Rulles_simples_random_сount_rules"]));
            }
            set {
                this["Generator_Rulles_simples_random_сount_rules"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int init_by_samples_conf_Type_func {
            get {
                return ((int)(this["init_by_samples_conf_Type_func"]));
            }
            set {
                this["init_by_samples_conf_Type_func"] = value;
            }
        }
    }
}
