//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EsMethods.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    public sealed partial class SettingsBase : global::System.Configuration.ApplicationSettingsBase {
        
        private static SettingsBase defaultInstance = ((SettingsBase)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new SettingsBase())));
        
        public static SettingsBase Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int ES_method_Count_Multipoint {
            get {
                return ((int)(this["ES_method_Count_Multipoint"]));
            }
            set {
                this["ES_method_Count_Multipoint"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int ES_method_Count_iteration {
            get {
                return ((int)(this["ES_method_Count_iteration"]));
            }
            set {
                this["ES_method_Count_iteration"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int ES_method_size_population {
            get {
                return ((int)(this["ES_method_size_population"]));
            }
            set {
                this["ES_method_size_population"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int ES_method_size_child {
            get {
                return ((int)(this["ES_method_size_child"]));
            }
            set {
                this["ES_method_size_child"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public double ES_method_conf_t {
            get {
                return ((double)(this["ES_method_conf_t"]));
            }
            set {
                this["ES_method_conf_t"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public double ES_method_conf_b {
            get {
                return ((double)(this["ES_method_conf_b"]));
            }
            set {
                this["ES_method_conf_b"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ES_method_Count_type_cross {
            get {
                return ((int)(this["ES_method_Count_type_cross"]));
            }
            set {
                this["ES_method_Count_type_cross"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.5")]
        public double ES_method_Count_uniform_level {
            get {
                return ((double)(this["ES_method_Count_uniform_level"]));
            }
            set {
                this["ES_method_Count_uniform_level"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ES_method_type_init {
            get {
                return ((int)(this["ES_method_type_init"]));
            }
            set {
                this["ES_method_type_init"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ES_method_type_mutate {
            get {
                return ((int)(this["ES_method_type_mutate"]));
            }
            set {
                this["ES_method_type_mutate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.5")]
        public double ES_method_b_rotate {
            get {
                return ((double)(this["ES_method_b_rotate"]));
            }
            set {
                this["ES_method_b_rotate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ES_Used {
            get {
                return ((bool)(this["ES_Used"]));
            }
            set {
                this["ES_Used"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int ES_Used_times {
            get {
                return ((int)(this["ES_Used_times"]));
            }
            set {
                this["ES_Used_times"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int HybrideSendEach {
            get {
                return ((int)(this["HybrideSendEach"]));
            }
            set {
                this["HybrideSendEach"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int HybrideGetEach {
            get {
                return ((int)(this["HybrideGetEach"]));
            }
            set {
                this["HybrideGetEach"] = value;
            }
        }
    }
}
