//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RandomMethods.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class SettingsBase : global::System.Configuration.ApplicationSettingsBase {
        
        private static SettingsBase defaultInstance = ((SettingsBase)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new SettingsBase())));
        
        public static SettingsBase Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int consq_Config_Random_Search_count_iteration {
            get {
                return ((int)(this["consq_Config_Random_Search_count_iteration"]));
            }
            set {
                this["consq_Config_Random_Search_count_iteration"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int consq_Config_Random_Search_count_generate_by_iteration {
            get {
                return ((int)(this["consq_Config_Random_Search_count_generate_by_iteration"]));
            }
            set {
                this["consq_Config_Random_Search_count_generate_by_iteration"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int Term_Config_Random_Search_count_iteration {
            get {
                return ((int)(this["Term_Config_Random_Search_count_iteration"]));
            }
            set {
                this["Term_Config_Random_Search_count_iteration"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int Term_Config_Random_Search_count_generate_by_iteration {
            get {
                return ((int)(this["Term_Config_Random_Search_count_generate_by_iteration"]));
            }
            set {
                this["Term_Config_Random_Search_count_generate_by_iteration"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int Weigths_Config_Random_Search_count_iteration {
            get {
                return ((int)(this["Weigths_Config_Random_Search_count_iteration"]));
            }
            set {
                this["Weigths_Config_Random_Search_count_iteration"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int Weigths_Config_Random_Search_count_generate_by_iteration {
            get {
                return ((int)(this["Weigths_Config_Random_Search_count_generate_by_iteration"]));
            }
            set {
                this["Weigths_Config_Random_Search_count_generate_by_iteration"] = value;
            }
        }
    }
}
