//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RandomMethods.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class SettingsBase : global::System.Configuration.ApplicationSettingsBase {
        
        private static SettingsBase defaultInstance = ((SettingsBase)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new SettingsBase())));
        
        public static SettingsBase Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int consq_Config_Random_Search_count_iteration {
            get {
                return ((int)(this["consq_Config_Random_Search_count_iteration"]));
            }
            set {
                this["consq_Config_Random_Search_count_iteration"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int consq_Config_Random_Search_count_generate_by_iteration {
            get {
                return ((int)(this["consq_Config_Random_Search_count_generate_by_iteration"]));
            }
            set {
                this["consq_Config_Random_Search_count_generate_by_iteration"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300")]
        public int count_iterations {
            get {
                return ((int)(this["count_iterations"]));
            }
            set {
                this["count_iterations"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40")]
        public int count_particles {
            get {
                return ((int)(this["count_particles"]));
            }
            set {
                this["count_particles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int Weigths_Config_Random_Search_count_iteration {
            get {
                return ((int)(this["Weigths_Config_Random_Search_count_iteration"]));
            }
            set {
                this["Weigths_Config_Random_Search_count_iteration"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int Weigths_Config_Random_Search_count_generate_by_iteration {
            get {
                return ((int)(this["Weigths_Config_Random_Search_count_generate_by_iteration"]));
            }
            set {
                this["Weigths_Config_Random_Search_count_generate_by_iteration"] = value;
            }
        }
    }
}
