//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeesMethods.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    public sealed partial class SettingsBase : global::System.Configuration.ApplicationSettingsBase {
        
        private static SettingsBase defaultInstance = ((SettingsBase)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new SettingsBase())));
        
        public static SettingsBase Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int ABCW_Search_count_iter {
            get {
                return ((int)(this["ABCW_Search_count_iter"]));
            }
            set {
                this["ABCW_Search_count_iter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int ABCW_Search_count_hive {
            get {
                return ((int)(this["ABCW_Search_count_hive"]));
            }
            set {
                this["ABCW_Search_count_hive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40")]
        public double ABCW_Search_part_scout {
            get {
                return ((double)(this["ABCW_Search_part_scout"]));
            }
            set {
                this["ABCW_Search_part_scout"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("70")]
        public double ABCW_Search_init_temperature {
            get {
                return ((double)(this["ABCW_Search_init_temperature"]));
            }
            set {
                this["ABCW_Search_init_temperature"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.9")]
        public double ABCW_Searcg_cold_coeff {
            get {
                return ((double)(this["ABCW_Searcg_cold_coeff"]));
            }
            set {
                this["ABCW_Searcg_cold_coeff"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public double ABCW_g_coef {
            get {
                return ((double)(this["ABCW_g_coef"]));
            }
            set {
                this["ABCW_g_coef"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.01")]
        public double ABCW_Border1 {
            get {
                return ((double)(this["ABCW_Border1"]));
            }
            set {
                this["ABCW_Border1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.05")]
        public double ABCW_Border2 {
            get {
                return ((double)(this["ABCW_Border2"]));
            }
            set {
                this["ABCW_Border2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.1")]
        public double ABCW_Border3 {
            get {
                return ((double)(this["ABCW_Border3"]));
            }
            set {
                this["ABCW_Border3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int ABCW_Repeat1 {
            get {
                return ((int)(this["ABCW_Repeat1"]));
            }
            set {
                this["ABCW_Repeat1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int ABCW_Repeat2 {
            get {
                return ((int)(this["ABCW_Repeat2"]));
            }
            set {
                this["ABCW_Repeat2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ABCW_Repeat3 {
            get {
                return ((int)(this["ABCW_Repeat3"]));
            }
            set {
                this["ABCW_Repeat3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.8")]
        public double ABCW_propability_tournament {
            get {
                return ((double)(this["ABCW_propability_tournament"]));
            }
            set {
                this["ABCW_propability_tournament"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int ABCW_TypeSelect {
            get {
                return ((int)(this["ABCW_TypeSelect"]));
            }
            set {
                this["ABCW_TypeSelect"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int ABCS_CountScout {
            get {
                return ((int)(this["ABCS_CountScout"]));
            }
            set {
                this["ABCS_CountScout"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int ABCS_CountWorkers {
            get {
                return ((int)(this["ABCS_CountWorkers"]));
            }
            set {
                this["ABCS_CountWorkers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int ABCS_CountRulesAdd {
            get {
                return ((int)(this["ABCS_CountRulesAdd"]));
            }
            set {
                this["ABCS_CountRulesAdd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ABCS_TypeTerms {
            get {
                return ((int)(this["ABCS_TypeTerms"]));
            }
            set {
                this["ABCS_TypeTerms"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ABCS_Used {
            get {
                return ((bool)(this["ABCS_Used"]));
            }
            set {
                this["ABCS_Used"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int ABCS_UsedTimes {
            get {
                return ((int)(this["ABCS_UsedTimes"]));
            }
            set {
                this["ABCS_UsedTimes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int ABCP_hiveSize {
            get {
                return ((int)(this["ABCP_hiveSize"]));
            }
            set {
                this["ABCP_hiveSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public double ABCP_percentScouts {
            get {
                return ((double)(this["ABCP_percentScouts"]));
            }
            set {
                this["ABCP_percentScouts"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("70")]
        public double ABCP_initTemp {
            get {
                return ((double)(this["ABCP_initTemp"]));
            }
            set {
                this["ABCP_initTemp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.95")]
        public double ABCP_coeffTemp {
            get {
                return ((double)(this["ABCP_coeffTemp"]));
            }
            set {
                this["ABCP_coeffTemp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public int ABCP_iterration {
            get {
                return ((int)(this["ABCP_iterration"]));
            }
            set {
                this["ABCP_iterration"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ABCP_selectionType {
            get {
                return ((int)(this["ABCP_selectionType"]));
            }
            set {
                this["ABCP_selectionType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.001")]
        public double ABCP_Border1 {
            get {
                return ((double)(this["ABCP_Border1"]));
            }
            set {
                this["ABCP_Border1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.05")]
        public double ABCP_Border2 {
            get {
                return ((double)(this["ABCP_Border2"]));
            }
            set {
                this["ABCP_Border2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.3")]
        public double ABCP_Border3 {
            get {
                return ((double)(this["ABCP_Border3"]));
            }
            set {
                this["ABCP_Border3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int ABCP_Repeat1 {
            get {
                return ((int)(this["ABCP_Repeat1"]));
            }
            set {
                this["ABCP_Repeat1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int ABCP_Repeat2 {
            get {
                return ((int)(this["ABCP_Repeat2"]));
            }
            set {
                this["ABCP_Repeat2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ABCP_Repeat3 {
            get {
                return ((int)(this["ABCP_Repeat3"]));
            }
            set {
                this["ABCP_Repeat3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int ABCS_HybrideSendEach {
            get {
                return ((int)(this["ABCS_HybrideSendEach"]));
            }
            set {
                this["ABCS_HybrideSendEach"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int ABCS_HybrideGetEach {
            get {
                return ((int)(this["ABCS_HybrideGetEach"]));
            }
            set {
                this["ABCS_HybrideGetEach"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int ABCDS_Iter {
            get {
                return ((int)(this["ABCDS_Iter"]));
            }
            set {
                this["ABCDS_Iter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int ABCDS_CountWorkers {
            get {
                return ((int)(this["ABCDS_CountWorkers"]));
            }
            set {
                this["ABCDS_CountWorkers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int ABCDS_CountScout {
            get {
                return ((int)(this["ABCDS_CountScout"]));
            }
            set {
                this["ABCDS_CountScout"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int ABCDS_CountOfBestBase {
            get {
                return ((int)(this["ABCDS_CountOfBestBase"]));
            }
            set {
                this["ABCDS_CountOfBestBase"] = value;
            }
        }
    }
}
