//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnionAndUnCrossTermsMethods.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40")]
        public double Pareto_simpler_UnionTerms_byBorderPercent {
            get {
                return ((double)(this["Pareto_simpler_UnionTerms_byBorderPercent"]));
            }
            set {
                this["Pareto_simpler_UnionTerms_byBorderPercent"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public double Pareto_simpler_UnionTerms_bySqarePercent {
            get {
                return ((double)(this["Pareto_simpler_UnionTerms_bySqarePercent"]));
            }
            set {
                this["Pareto_simpler_UnionTerms_bySqarePercent"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Pareto_simpler_BreakTheCross {
            get {
                return ((bool)(this["Pareto_simpler_BreakTheCross"]));
            }
            set {
                this["Pareto_simpler_BreakTheCross"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Pareto_simpler_UnionTerms {
            get {
                return ((bool)(this["Pareto_simpler_UnionTerms"]));
            }
            set {
                this["Pareto_simpler_UnionTerms"] = value;
            }
        }
    }
}
