//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mix_core.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int init_by_samples_conf_Type_func {
            get {
                return ((int)(this["init_by_samples_conf_Type_func"]));
            }
            set {
                this["init_by_samples_conf_Type_func"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int Global_count_restart {
            get {
                return ((int)(this["Global_count_restart"]));
            }
            set {
                this["Global_count_restart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool init_everyone_with_everyone_check {
            get {
                return ((bool)(this["init_everyone_with_everyone_check"]));
            }
            set {
                this["init_everyone_with_everyone_check"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int init_everyone_with_everyone_func {
            get {
                return ((int)(this["init_everyone_with_everyone_func"]));
            }
            set {
                this["init_everyone_with_everyone_func"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool save_log_check {
            get {
                return ((bool)(this["save_log_check"]));
            }
            set {
                this["save_log_check"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Index0_add_algorithm {
            get {
                return ((int)(this["Index0_add_algorithm"]));
            }
            set {
                this["Index0_add_algorithm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Index0_learn_algorithm {
            get {
                return ((int)(this["Index0_learn_algorithm"]));
            }
            set {
                this["Index0_learn_algorithm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Index1_learn_algorithm {
            get {
                return ((int)(this["Index1_learn_algorithm"]));
            }
            set {
                this["Index1_learn_algorithm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool save_FS_check {
            get {
                return ((bool)(this["save_FS_check"]));
            }
            set {
                this["save_FS_check"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Generator_Rulles_simples_random_func {
            get {
                return ((int)(this["Generator_Rulles_simples_random_func"]));
            }
            set {
                this["Generator_Rulles_simples_random_func"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Generator_Rulles_simples_random_stable {
            get {
                return ((int)(this["Generator_Rulles_simples_random_stable"]));
            }
            set {
                this["Generator_Rulles_simples_random_stable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int Generator_Rulles_simples_random_сount_rules {
            get {
                return ((int)(this["Generator_Rulles_simples_random_сount_rules"]));
            }
            set {
                this["Generator_Rulles_simples_random_сount_rules"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int Term_Config_Random_Search_count_iteration {
            get {
                return ((int)(this["Term_Config_Random_Search_count_iteration"]));
            }
            set {
                this["Term_Config_Random_Search_count_iteration"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int Term_Config_Random_Search_count_generate_by_iteration {
            get {
                return ((int)(this["Term_Config_Random_Search_count_generate_by_iteration"]));
            }
            set {
                this["Term_Config_Random_Search_count_generate_by_iteration"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int consq_Config_Random_Search_count_iteration {
            get {
                return ((int)(this["consq_Config_Random_Search_count_iteration"]));
            }
            set {
                this["consq_Config_Random_Search_count_iteration"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int consq_Config_Random_Search_count_generate_by_iteration {
            get {
                return ((int)(this["consq_Config_Random_Search_count_generate_by_iteration"]));
            }
            set {
                this["consq_Config_Random_Search_count_generate_by_iteration"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public int PSO_population {
            get {
                return ((int)(this["PSO_population"]));
            }
            set {
                this["PSO_population"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public int PSO_iter {
            get {
                return ((int)(this["PSO_iter"]));
            }
            set {
                this["PSO_iter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.6")]
        public double PSO_c1 {
            get {
                return ((double)(this["PSO_c1"]));
            }
            set {
                this["PSO_c1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.8")]
        public double PSO_c2 {
            get {
                return ((double)(this["PSO_c2"]));
            }
            set {
                this["PSO_c2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int Pareto_simpler_Request_count_rules {
            get {
                return ((int)(this["Pareto_simpler_Request_count_rules"]));
            }
            set {
                this["Pareto_simpler_Request_count_rules"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int init_everyone_with_everyone_agv_count_terms {
            get {
                return ((int)(this["init_everyone_with_everyone_agv_count_terms"]));
            }
            set {
                this["init_everyone_with_everyone_agv_count_terms"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int Term_shrink_and_rotate_conf_count_shrink {
            get {
                return ((int)(this["Term_shrink_and_rotate_conf_count_shrink"]));
            }
            set {
                this["Term_shrink_and_rotate_conf_count_shrink"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int Term_shrink_and_rotate_conf_size_of_shrink {
            get {
                return ((int)(this["Term_shrink_and_rotate_conf_size_of_shrink"]));
            }
            set {
                this["Term_shrink_and_rotate_conf_size_of_shrink"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int k_mean_rules_generator_conf_type_func {
            get {
                return ((int)(this["k_mean_rules_generator_conf_type_func"]));
            }
            set {
                this["k_mean_rules_generator_conf_type_func"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int k_mean_rules_generator_conf_count_rules {
            get {
                return ((int)(this["k_mean_rules_generator_conf_count_rules"]));
            }
            set {
                this["k_mean_rules_generator_conf_count_rules"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int k_mean_rules_generator_conf_type_alg {
            get {
                return ((int)(this["k_mean_rules_generator_conf_type_alg"]));
            }
            set {
                this["k_mean_rules_generator_conf_type_alg"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public double k_mean_rules_generator_conf_nebulisation_factor {
            get {
                return ((double)(this["k_mean_rules_generator_conf_nebulisation_factor"]));
            }
            set {
                this["k_mean_rules_generator_conf_nebulisation_factor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int k_mean_rules_generator_conf_Max_iterate {
            get {
                return ((int)(this["k_mean_rules_generator_conf_Max_iterate"]));
            }
            set {
                this["k_mean_rules_generator_conf_Max_iterate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1E-06")]
        public double k_mean_rules_generator_conf_need_precision {
            get {
                return ((double)(this["k_mean_rules_generator_conf_need_precision"]));
            }
            set {
                this["k_mean_rules_generator_conf_need_precision"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int ES_method_size_population {
            get {
                return ((int)(this["ES_method_size_population"]));
            }
            set {
                this["ES_method_size_population"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15")]
        public int ES_method_size_child {
            get {
                return ((int)(this["ES_method_size_child"]));
            }
            set {
                this["ES_method_size_child"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public double ES_method_conf_t {
            get {
                return ((double)(this["ES_method_conf_t"]));
            }
            set {
                this["ES_method_conf_t"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public double ES_method_conf_b {
            get {
                return ((double)(this["ES_method_conf_b"]));
            }
            set {
                this["ES_method_conf_b"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int ES_method_Count_iteration {
            get {
                return ((int)(this["ES_method_Count_iteration"]));
            }
            set {
                this["ES_method_Count_iteration"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ES_method_Count_type_cross {
            get {
                return ((int)(this["ES_method_Count_type_cross"]));
            }
            set {
                this["ES_method_Count_type_cross"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.3")]
        public double ES_method_Count_uniform_level {
            get {
                return ((double)(this["ES_method_Count_uniform_level"]));
            }
            set {
                this["ES_method_Count_uniform_level"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40")]
        public int ES_method_Count_Multipoint {
            get {
                return ((int)(this["ES_method_Count_Multipoint"]));
            }
            set {
                this["ES_method_Count_Multipoint"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ES_method_type_init {
            get {
                return ((int)(this["ES_method_type_init"]));
            }
            set {
                this["ES_method_type_init"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.3")]
        public string ES_method_Count_Унифицированный_level {
            get {
                return ((string)(this["ES_method_Count_Унифицированный_level"]));
            }
            set {
                this["ES_method_Count_Унифицированный_level"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ES_method_type_mutate {
            get {
                return ((int)(this["ES_method_type_mutate"]));
            }
            set {
                this["ES_method_type_mutate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public double ES_method_b_rotate {
            get {
                return ((double)(this["ES_method_b_rotate"]));
            }
            set {
                this["ES_method_b_rotate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Load_UFS_file_name {
            get {
                return ((string)(this["Load_UFS_file_name"]));
            }
            set {
                this["Load_UFS_file_name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int Weigths_Config_Random_Search_count_iteration {
            get {
                return ((int)(this["Weigths_Config_Random_Search_count_iteration"]));
            }
            set {
                this["Weigths_Config_Random_Search_count_iteration"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int Weigths_Config_Random_Search_count_generate_by_iteration {
            get {
                return ((int)(this["Weigths_Config_Random_Search_count_generate_by_iteration"]));
            }
            set {
                this["Weigths_Config_Random_Search_count_generate_by_iteration"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Index1_add_algorithm {
            get {
                return ((int)(this["Index1_add_algorithm"]));
            }
            set {
                this["Index1_add_algorithm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Index2_learn_algorithm {
            get {
                return ((int)(this["Index2_learn_algorithm"]));
            }
            set {
                this["Index2_learn_algorithm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int count_repeate_full_cirle {
            get {
                return ((int)(this["count_repeate_full_cirle"]));
            }
            set {
                this["count_repeate_full_cirle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Index4_learn_algorithm {
            get {
                return ((int)(this["Index4_learn_algorithm"]));
            }
            set {
                this["Index4_learn_algorithm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MultiSelectFolder {
            get {
                return ((string)(this["MultiSelectFolder"]));
            }
            set {
                this["MultiSelectFolder"] = value;
            }
        }
    }
}
